databases:
  - name: todo_listdb
    plan: free
    databaseName: todo_list
    user: todo_list

services:
  - type: web
    plan: free
    name: todo_list
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn todo_list.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo_listdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4